* [Home](.)
* [Commands](Commands)
* [Games setup](Games-setup)
* [External FFB mode](External-ffb-mode)
* [Setup](Setup)
  * [DFU firmware update](Setup#dfu-driver-installation)
  * [TMC4671 setup](Setup#wheel-setup-with-tmc4671)
  * [ODrive setup](Setup#odrive-setup)
* [Pinouts and peripherals](Pinouts-and-peripherals)
  * Inputs
    * [Buttons](Pinouts-and-peripherals#digital-buttons)
    * [Analog pins](Pinouts-and-peripherals#analog-inputs)
    * [Shifter](Pinouts-and-peripherals#analog-shifter)
    * [SPI buttons](Pinouts-and-peripherals#spi-buttons)
    * [I²C PCF8574](Pinouts-and-peripherals#i2c-pcf8574)
  * Motor drivers
    * [PWM](Pinouts-and-peripherals#pwm-mode)
    * [Simplemotion](Pinouts-and-peripherals#granite-simplemotion)
    * [VESC & ODrive (CAN)](Pinouts-and-peripherals#can-bus)
* [FAQ](FAQ)
* [Changelog](Changelog)
* [TMC debug mode](TMCL-IDE-debugging)